apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks--nextjshelloworld-deployment
  namespace: helloworld-eks-app
  labels:
    app: helloworld-eks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-eks-app
  template:
    metadata:
      labels:
        app:helloworld-eks-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: helloworldnextjs
        image: account.dkr.ecr.us-east-1.amazonaws.com/ecrreponame
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux